language: node_js
node_js:
- '8.1.2'
- '8'
- '9'
before_script:
- npm run lint
after_script:
- npm run coveralls
deploy:
  provider: npm
  email: jhaugh42@gmail.com
  api_key:
    secure: gs4fn2OlvWeXEaYqv6cufvmRVleNv4tdhlwIPYToxskPxxmSV8VfNxgictsIrSZnCsZ9ZEWQmcbh6I3isX4v+FxYygmU91frMXL0MmLwGerCmqzURmyU7Uf6soQ/W2a277ae1o6JpgiAa+YgOzqDg1NTou4iz17mlC3Zk/gddpwy7n95MVoA9HLWF8G8BePPKjueht0RUV+zl/qypkCkvEAGaiW3vupR/TaffkY85iP3WeChciqHyUn4A/KdyctIaZTFFVsOSiPzDvEGTG/GDbe6taud9M9qQZnF4KQx2SW/rD3I708buIcE7rXehD9jBsjEdFdhalMaidem4iDLyn9q+pG7pRbINo8rxWJGLfuXk7Qe7k+huyVNuV/W8bgTZy5KdIGQRrSPhttlFa6JW2rQpCe2IEeoL0pPilaCpYc0XmuwxekBctHrJo6+5bbH4RYXqHSXACBsnL5jk26WGGBJ5sGk5MAlABqd5ks2n+h/hEs88W+DfJ9rqvk+C0CKYUeS2vcO5JLLvZGFZS0ibrKXYrKySC0hMJxFFcqlAhHpWgsYyBgUOR20V7RfViOMDk7c2DXNzOv2X8Lak/dE8VmhKsA+aSqslqGkCIJbJNGQ1uvUhMwtlbz3CI1/Ro+qWXuGfCtYzpMq1BojXyvVVHJP1WmUgk77+q5mC+xdIFU=
  on:
    tags: true
    repo: GannettDigital/palinode
