language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
- '0.12'
before_script:
- npm run lint
after_script:
- npm run coveralls
deploy:
  provider: npm
  email: jhaugh42@gmail.com
  api_key:
    secure: WAzZrugCODo04yfxcWKGEcqomsph9NAgQBs3doBJoc6uJlNSXMBg6MaFzuuI8kiXhGmawimxGMvEgahZIQFg01imIdh83Rwr3Fg/o1RuHD1sXW03YwQs/MhyPb40qzrNzSX/dJED1eMdKDyyTBO47gI72vPHQWv8moANuI12lzocrZZYGr6sK84agc5CPkiJuNOZcPp7eWYhpS6XTBdKZ1Z7JFeb6fR4WeJ5CWE72ia5wt/F4NxySlzyCJObwD4xHXC4HCfnWW2ympLmu7oddVc/IKrmDHtvyx8JtgBIq5qte+oHXzk9ow+CfG7p+QI5RBhJu5micJewcBGAj0bvG6WiIsYRFIN+zan3tDp96Xiy5xIvy8BV5nnNMaE9WrtJHKgXkDtlvg1qIJAESb5huvAIfZTRjj0V9CvoIVljBoxEzp8vBPU+WxFS72/YlRm7oG/dzE4csogA9jIO9ohU/xZ1WgX3EWjLzozln9N+Cu1URQK1HTE6o2a7OmjbYjmwRtajMiHYQCkJ/arhYI8RgQEeNrgAcFCqnKSSWMfMkRmHLqgkzDzYr/7rIyp7AsVqG6bpPGfq4FVsnL97Km/lNB7WfGWX40YL8cmSML5BaGX65OKVoDo+oMDiI9J6RfhmOhTB7/0Dl7dqX5XPE5lCbVi6gnGmvlknNwvZLVAdqPk=
  on:
    tags: true
    repo: GannettDigital/palinode
